### ISSUE TITLE
Don't write timestamp to file header

### ISSUE THREAD

**Issue by tobtoht** [plougher/squashfs-tools#105]
Objective: create reproducible squashfs (matching digests)

Create two squashfs from the same directory
```
$ mksquashfs test/ test.squashfs.1 -fstime 0 -noappend -root-owned
$ mksquashfs test/ test.squashfs.2 -fstime 0 -noappend -root-owned
```
Both files only differ in the file header:
```
$ xxd test.squashfs.1 | head -n 1
00000000: 6873 7173 0200 0000 **8ceb 0660** 0000 0200  hsqs.......`....

$ xxd test.squashfs.2 | head -n 1
00000000: 6873 7173 0200 0000 **78eb 0660** 0000 0200  hsqs....x..`....
```
This appears to be a timestamp
```
$ unsquashfs -s test.squashfs.1
Creation or last append time **Tue Jan 19 09:54:12 2021**
```

Workaround:
```
$ printf '\x00\x00\x00\x00' | dd conv=notrunc of=test.squashfs.1 bs=1 seek=$((0x8))
```

Is there an option to disable this behavior?

squashfs-tools version: 38fa07205 (latest master)

**Comment by plougher** [comment]
The above works for me.

<pre>
phillip@phoenix:~/github$ mksquashfs -version
mksquashfs version 4.4-38fa072 (2021-01-18)
copyright (C) 2021 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

phillip@phoenix:~/github$ mksquashfs squashfs-tools 1.sqsh -quiet -no-progress -fstime 0 -noappend -root-owned
phillip@phoenix:~/github$ mksquashfs squashfs-tools 2.sqsh -quiet -no-progress -fstime 0 -noappend -root-owned
phillip@phoenix:~/github$ cp 1.sqsh 2.sqsh
phillip@phoenix:~/github$ unsquashfs -fstime 1.sqsh
0
phillip@phoenix:~/github$ unsquashfs -fstime 2.sqsh
0
</pre>
</pre>

If the mksquashfs command lines had "-fstime 0" then the timestamp in the filesystem will be zero, and not today's date.

I think you have mistyped the commands.
