### ISSUE TITLE
Non-fatal errors: use different error codes?

### ISSUE THREAD

**Issue by armijnhemel** [plougher/squashfs-tools#107]
As was mentioned in #94 it makes complete sense to harden error checking in unsquashfs. Like the reporter I also got bitten by this (I have tools that wrap around unsquashfs and they stopped working). Although the -no-exit-code option works around it I can imagine it is not the cleanest solution.

What could help if there would be a distinction between fatal and non-fatal errors, for example use exit code 1 for fatal and 2 for non-fatal. Personally I have no interest in having backwards compatibility with 4.3.

**Comment by plougher** [comment]
Having fatal and non-fatal errors return different exit codes is a good idea :)

I'll have a look to see how easy it is to do (it should be easy).

**Comment by plougher** [comment]
Does the above commit do what you want?  Feel free to close this issue if it does.  Otherwise, comment on why it doesn't.  Thanks.

**Comment by armijnhemel** [comment]
I will compile and test :)

**Comment by armijnhemel** [comment]
Works as expected, thanks!
