### ISSUE TITLE
mksquashfs -h prints to stderr

### ISSUE THREAD

**Issue by johnrichardrinehart** [plougher/squashfs-tools#111]
`mksquashfs -h | less` doesn't allow navigating through `print_options` because it prints to `stderr` instead of `stdout`.

Would you consider changing the behavior of the `squashfs` tools to print usage instructions to `stdout`, instead?

I'm guessing not, since the behavior looks [very intentional](https://github.com/plougher/squashfs-tools/blob/6a3d5d06bde3444bd939e9d9e72583619413484a/squashfs-tools/mksquashfs.c#L5474). If you won't consider printing to `stdout` could you please advise on why this is preferred behavior?

Thank you for your tools!

**Comment by johnrichardrinehart** [comment]
Please note that the GNU standards on CLIs recommends that help usage [be printed to `stdout`](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html).

**Comment by plougher** [comment]
I have implemented -help and -h options which output to stdout as expected.

Please refer to the above commit for background information as to why it was originally done differently.

**Comment by johnrichardrinehart** [comment]
@plougher Ah, I didn't even notice that `-h` wasn't an option. Thanks for implementing this!
