### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [plougher/squashfs-tools#112]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by plougher** [comment]
I'm working on a new release now.  Most development for the release is finished, and I'm into the testing, documentation, and fix (where issues come to light in testing) phase.  Time spent here makes a better release, and ultimately less complaints and bug reports raised :)

I'll leave this issue open, and close it when the release is done.

**Comment by kloczek** [comment]
Thx :)

**Comment by plougher** [comment]
I know it took a long time to make the final release.  But, most of the last few months was testing to ensure the release was as correct as I could make it.  I have had very few bug reports after the release, which suggests the strategy did work :)
