### ISSUE TITLE
Unable to load squashfs as a kernel module

### ISSUE THREAD

**Issue by kklodowski** [plougher/squashfs-tools#116]
Hi,

it's not really an issue with squashfs itself, but I would like to use it on a machine on which I'm not allowed to recompile the whole kernel. So I compiled squashfs as kernel module, but when I try to load it with `insmod` it prompts the following error:

![insmod_error](https://user-images.githubusercontent.com/84983123/120018289-dc9f3b80-bfde-11eb-91cc-ebcfc02ed1d4.png)

Maybe it's a matter of some missing dependencies but I couldn't figure out what could it be. Does anyone has an idea how to fix that?

Sorry if it's not the right place to ask, but the mailing list on sourceforge seems to be a bit outdated.

Best,
Krzysztof

**Comment by plougher** [comment]
As you said, this is a case of missing dependencies.  A quick google of some of the missing symbols brings up the kernel configuration option that may be responsible for producing that dependency.   But, the problem with the Linux kernel is that it is multi-layered, one configuration option pulls in another option (as a dependency), which pulls in yet another.  In other words it is often unclear where these dependencies are coming from.  AFAIK there is nothing in the kernel configuration infrastructure that will produce a dump of these derived dependencies.  You just have to work through the Kconfig files, which takes time.

The truth is you're going about this the wrong way.   The usual way is to take the kernel config file used to build the kernel, and then use that to build any additional modules.  In that way you know it will match.   Anything else will produce the problems you describe.

I'm not a great fan of this, and I have hit similar problems to what  you describe.  In particular trying to work out how a kernel was configured so I can rebuild it.

In otherwords you can have my sympathies, but I can't give you anything more.
