### ISSUE TITLE
No clear installation directions

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [plougher/squashfs-tools#130]
I read "Install" and all the readme files. There are no clear installation directions. Step 1, step 2, etc. Usually, I extract an archive and everything extracted is in one directory and there are clear step by step instructions in a text file in that directory. None of that is true here.  I want to try to install on a bare bones Ubuntu 18.04 built from the mini.iso with plain Openbox and no further DE.

**Comment by AgentD** [comment]
> I want to try to install on a bare bones Ubuntu 18.04

Your distribution already contains squashfs-tools 4.3 [in the package manager repository](https://launchpad.net/ubuntu/+source/squashfs-tools). It can be installed from there (e.g. using `apt get install`).

But I'll assume, you want to build it from source to get a recent version.

> Usually, I extract an archive and everything extracted is in one directory...

If you've done this often enough, you might have spotted some similarities in the steps by know. Let's apply some of that learnt knowledge here:

There is a `Makefile` in the sub-directory `squashfs-tools`, where all the source code is. You can run `make` to compile it.

Compressors other than `gzip` are disabled by default. At the start of the `Makefile`, [there are several variables to turn them on](https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/Makefile#L10), but they are commented out by default. If you want to enable additional compressors, you need to uncomment some variables here.

The compressors will need the development packages of the their respective libraries (e.g. `zlib`, `xz-utils`, ...). Ubuntu should have all of them in the repository.

Lastly, [the `Makefile` has an install target](https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/Makefile#L406). If you don't set the variable for the destination directory, [it defaults to `/usr/local/bin`](https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/Makefile#L156).

**Comment by haampie** [comment]
I've created a [spack recipe](https://github.com/spack/spack/) in case you want to build squashfs + its dependencies from sources. This gives you the general package info & variants you can configure:

```
spack info squashfs
```

and then you can install it like this:

```
spack install squashfs # defaults
spack install squashfs default_compression=zstd +gzip +lz4 +lzo +xz +zstd # custom
```

**Comment by plougher** [comment]
I think this has been adequately described in the INSTALL file and above.

In general to build and install you type "make install" as root in the squashfs-tools directory.

If you want to change the default install directory or the build defaults, alter the Makefile install target, and alter the defaults in the Makefile.  This is fully described in the INSTALL file and the Makefile.

In general these instructions are aimed at developers and builders who understand Makefiles and the usual build process.  If you have no experience of that, you should use the squashfs-tools packaged by your distribution.  Unless you are a developer or builder, you should have no reason not to use version provided by your distribution.
