### ISSUE TITLE
Segmentation fault in read_inode for small input archive

### ISSUE THREAD

**Issue by vlaci** [plougher/squashfs-tools#138]
Given the following [example archive](https://github.com/IoT-Inspector/unblob/raw/9d76d78f319bc01133bdf41e9eda18d872ba5fb6/tests/integration/filesystem/squashfs/squashfs_v3_le/__input__/squashfs_v3_le.bin) unsquashfs segfaults upon extraction.

I have bisected the issue to this commit: 53d2c82898acbdf717828407defb8ae1a1e7a566 which has been released as part of squashfs-tools 4.5. The issue isn't present in 4.4

Running with gdb results in the following backtrace which seems to be related to the changes introduced in the above commit
```
Thread 1 "unsquashfs" received signal SIGSEGV, Segmentation fault.
0x000000000040f85a in read_inode (start_block=<optimized out>, offset=<optimized out>) at unsquash-3.c:252
warning: Source file is more recent than executable.
252				i.data = inode->file_size;
```

**Comment by plougher** [comment]
This should now be fixed.
