### ISSUE TITLE
Squashfs Segfault

### ISSUE THREAD

**Issue by Ninja243** [plougher/squashfs-tools#14]
Running `mksquashfs chroot binary/live/filesystem.squashfs -comp xz -e boot` runs well until 99%, after which it fails, saying that it had a Segmentation Fault.
Screenshot attached below:

![photo_2016-10-10_09-37-19](https://cloud.githubusercontent.com/assets/14904204/19229354/2fa7338e-8ecd-11e6-9e1f-f1ea086ce48a.jpg)

Am I doing something wrong, or is this an actual bug?

**Comment by plougher** [comment]
Closing due to lack of further information.
