### ISSUE TITLE
Don't run mandb in build environment

### ISSUE THREAD

**Issue by AdrianVovk** [plougher/squashfs-tools#143]
I'm building squashfs-tools in a minimal build environment, and installing packages into a different directory than they'd end up at runtime. At runtime, manpages are at `/usr/share/man`, but at build time squashfs's manpages get installed to `/buildstream-install/usr/share/man`. This directory (`/buildstream-install`) should not leak out of the build environment in any way. Moreover, the rest of the system (including `/var`, where `mandb` would install its cache) is read only to ensure packages can't/don't break their build environment. So, running `mandb` during the build just doesn't work correctly in any scenario. Generating/updating caches is *not* the job of the package anyway, at least when being packaged into a distro (using the equivalent of `DESTDIR=` from packages w/ standard build systems)

squashfs-tools should not run `mandb` at build time. Or at least give a way for distros to disable this functionality

**Comment by plougher** [comment]
This has been fixed in the above commit.  Closing.
