### ISSUE TITLE
unsquashfs cannot write to existing directory

### ISSUE THREAD

**Issue by emiller-amd** [plougher/squashfs-tools#144]
Currently behavior is to error with "because File Exists".  It would preferable to be able to extract to an existing directory like tar.

**Comment by plougher** [comment]
To do this, use the -force (or -f option)

**Comment by emiller-amd** [comment]
Thanks for the pointer,  I'll RTFM more carefully.

**Comment by plougher** [comment]
No problem.  In fact I've added it to the file exists error message, so it is now more obvious, e.g.

FATAL ERROR: dir_scan: failed to make directory squashfs-root, because File exists
To overwrite, use -force (or -f) option
