### ISSUE TITLE
mount: Cannot allocate memory

### ISSUE THREAD

**Issue by jrversteegh** [plougher/squashfs-tools#16]
I created a squashfs with 15M files and 70M inodes:
```
mksquashfs landmap landmap.squashfs -all-root -Xcompression-level 1 -no-xattrs
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on landmap.squashfs, block size 131072.
[=========================================================================================================|] 15555402/15555402 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 27240298.23 Kbytes (26601.85 Mbytes)
	82.08% of uncompressed filesystem size (33185729.57 Kbytes)
Inode table size 329397814 bytes (321677.55 Kbytes)
	14.18% of uncompressed inode table size (-1972012503 bytes)
Directory table size 444542330 bytes (434123.37 Kbytes)
	36.84% of uncompressed directory table size (1206545289 bytes)
Number of duplicate files found 137608
Number of inodes 70777736
Number of files 15555403
Number of fragments 231166
Number of symbolic links  55199607
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 22726
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
```

Trying to mount it afterwards yields: 
```
failed: Cannot allocate memory
```

and in dmesg:
```
squashfs: SQUASHFS error: unable to read inode lookup table
```
System: linux mint, 4.4.0-59-generic x86_64, squashfs-tools 4.3-3-ubuntu2.

Is this expected for this inode count or is there an issue? Would be cool if it worked or if mksquashfs would complain that this was not a feasible file system to begin with.

**Comment by plougher** [comment]
> Is this expected for this inode count or is there an issue? Would be cool if it worked or if mksquashfs would complain that this was not a feasible file system to begin with.

With a compressed filesystem there are very few hard-and-fast limits.  It entirely depends on the mix of inodes and data, file size and the compression achieved.  Additionally, you have to distinguish between filesystem limits and implementation limits, there are code which is likely to break before filesystem limits are hit, and vice-versa.

As regards 70 million inodes, that is outside the anticipated max inode count in the design of the kernel code handling the "inode lookup table".    Simply put the code assumes it can kmalloc sufficient memory to store this table (which is a second order table), and this can't be done with 70 million inodes.  This is an unusual edge case where the inode count is very large, but the overall filesystem size is well within the max filesystem size.

This issue has only come up once before in 2013, and I discussed this in that thread on Sourceforge https://sourceforge.net/p/squashfs/bugs/51, which I believe you have found.

I will consider rewriting this code to handle a larger inode count.

But if you do not intend to export the mounted Squashfs filesystem via NFS, then there should be an immediate fix.  The inode lookup table is only generated with "exportable" Squashfs filesystems.  You can disable this with the -no-exports option, i.e.

%mksquashfs landmap landmap.squashfs -all-root -Xcompression-level 1 -no-xattrs -no-exports

This will eliminate the "failed: Cannot allocate memory" error.

**Comment by jrversteegh** [comment]
Thanks for the -no-exports suggestion! I had already managed to reduce the inode count from 70M to 15M by replacing soft links with hard links --the file set is a tile map with many small 256x256 png images that contains many duplicate empty tiles--, but that set might grow in the future, so this work around is much appreciated.
