### ISSUE TITLE
A few uninitialized memory issues

### ISSUE THREAD

**Issue by m94mni** [plougher/squashfs-tools#169]
Running sqfstar using a sanitizer I found a few places where memory accesses are made to uninitialized memory.

They were also sometime causing crashes in optimized builds.

In particular, some members of the inode_info at 
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/xattr.c#L622

and the entry->fragment at
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/caches-queues-lists.c#L174

and the inode->tar_file at
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar_xattr.c#L159

seem to be uninitialized.

At a minimum, adding
    memset(inode, 0, sizeof(struct inode_info));
at 
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/mksquashfs.c#L3147

plus
        memset(inode, 0, sizeof(struct inode_info));
at
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar.c#L238

and
        memset(file_buffer, 0, sizeof(struct file_buffer));
at
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar.c#L1445

seems to be enough to resolve the issue I'm seeing, but I feel there's a number of other mallocs without memset around the code that  may be problematic. Or, alternatively, the right approach is to manually initialize the missing members.

**Comment by plougher** [comment]
> Running sqfstar using a sanitizer I found a few places where memory accesses are made to uninitialized memory.
> 
> They were also sometime causing crashes in optimized builds.
> 

Are you using the latest source code from Git?  Because those issues have already been reported and fixed in the following commits.

> In particular, some members of the inode_info at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/xattr.c#L622

Fixed in commit 75951fb96de64e8062306359c87d987b527a42d0
> 
> and the entry->fragment at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/caches-queues-lists.c#L174

Fixed in commit b978026fc392a50724d7d27b07530277905f605e

> 
> and the inode->tar_file at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar_xattr.c#L159
> 

Fixed in commit ab0784a046c9b107048ddac1611982021bd6492c

> seem to be uninitialized.
> 
> At a minimum, adding memset(inode, 0, sizeof(struct inode_info)); at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/mksquashfs.c#L3147
> 
> plus memset(inode, 0, sizeof(struct inode_info)); at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar.c#L238
> 
> and memset(file_buffer, 0, sizeof(struct file_buffer)); at https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/tar.c#L1445
> 
> seems to be enough to resolve the issue I'm seeing, but I feel there's a number of other mallocs without memset around the code that may be problematic. Or, alternatively, the right approach is to manually initialize the missing members.

**Comment by m94mni** [comment]
Right, I am not, I'm running 4.5. Is there a stable later version that makes sense to use rather than HEAD?

**Comment by plougher** [comment]
There will be a new release (4.5.1) tomorrow.  The last month has been spent testing and stabilising HEAD.
