### ISSUE TITLE
unsquashfs failed: xz uncompress failed with error code 9

### ISSUE THREAD

**Issue by zhangqiang-316** [plougher/squashfs-tools#179]
dear sir,

when I  exe unsquashfs, it failed as bellow info:

[root@localhost /]# unsquashfs /tmp/LiveOS/squashfs.img 
Parallel unsquashfs: Using 4 processors
1 inodes (80016 blocks) to write

[=======================================|                                                                                                                                         ] 17903/80016  22%
xz uncompress failed with error code 9
[============================================/   

How can I resolve this issue,  I have a long time can not resolve it!    please help me, thank you very much~

**Comment by plougher** [comment]
> xz uncompress failed with error code 9

Error code 9 is LZMA_DATA_ERROR.   This will be output by XZ if it has detected that the input data is corrupt.

It is more than likely the Squashfs filesystem is corrupted.  The only way to fix this is to get an uncorrupted version.
