### ISSUE TITLE
Support for symlinks in pseudo mode

### ISSUE THREAD

**Issue by mbj** [plougher/squashfs-tools#18]
For various reasons I do want to be able to build a squashfs image on the fly without ever having to read in files from my file system.

The pseudo file support gets me very far already, the only thing missing for now is the ability to define symlinks via pseudo files.

Questions:

* Would a PR adding that above feature be accepted?
* What would be the preferred implementation path?

I see that the internal pseudo structure `pseudo_dev` naming wise is biased towards device nodes, but it also contains the `command` field that is only used for files, hene this structure is already dealing with non device node specific tasks. So should a PR simply extend the existing `pseudo_dev` structure or attempt to clean it up (like finding a better name for it)?

**Comment by plougher** [comment]
What is a PR?  A Project Request requesting a new feature?

Well you should be glad to know  I looked at the request to implement pseudo symlinks and decided it shouldn't take more than an hour to do, as the infrastructure is already in place, and so did it and pushed it to the repository.  So you should now be able to create pseudo symlinks :-).

Pseudo files were originally implemented as people wanted to be able to create device nodes.  Over time the functionally has been extended to do other things, but nobody has wanted the ability to create pseudo symlinks before.   But as I said, the infrastructure already exists, and it was easy to extend it to support symlinks.

As far as naming in pseduo_dev is concerned, the command field is used by dynamic pseudo files, where the content of the file is produced by running the command specified in the pseudo definition.  The command field holds that command, and so the naming of the field is self-explanatory and entirely correct.

For symlinks an additional field called symlink has been created which contains the symlink, and the naming of the field again makes it self-explanatory.

But, command and symlink are never both used in the same pseudo_dev, and so these have been made an anonymous union, which doesn't require any extra space in the structure.

**Comment by mbj** [comment]
@plougher A PR is a "Pull Request" github terminology for me pushing a branch to my fork of your repo and asking you to "Pull" it into your master branch after review.

Your commit looks almost exactly like what I had locally, but I missed the opportunity to use a union in the struct. Thx for your time! I was about to do it myself and you beat me to it with a better version. Thx.
