### ISSUE TITLE
download url inconsistency

### ISSUE THREAD

**Issue by haampie** [plougher/squashfs-tools#181]
The filename in the latest release https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.5.1/squashfs-tools-4.5.1.tar.gz/download is inconsistent with others due to the `-tools` suffix. Package managers may need to special case this download. Can the standard url also be made available?

**Comment by plougher** [comment]
Added https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.5.1/squashfs4.5.1.tar.gz/download
