### ISSUE TITLE
Calls to close in mksquashfs.c should check for errors

### ISSUE THREAD

**Issue by struktured** [plougher/squashfs-tools#182]
When running mksquashfs over a s3 fuse filesytem, s3 returned a 403 which prevented the `close` call from succeeding. However, `mksquashfs` ignored this error and acted as if the operation completed successfully. To be clear, nothing at all ultimately got written to the destination filesystem. 

Here is where I suspect the close failed:

https://github.com/plougher/squashfs-tools/blob/188454662ed6de1332fe72dc119977b5ccb5fb1d/squashfs-tools/mksquashfs.c#L8033

Another unguarded close is here too:
https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/mksquashfs.c#L6966

**Comment by plougher** [comment]
As is mentioned in "man 2 close"

```
Note, however, that a failure return should be used only for diagnostic purposes (i.e., a warning to
the  application that there  may still be I/O pending or there may have been failed I/O) or remedial
purposes (e.g., writing the file once more or creating a backup).

Retrying the close() after a failure return is the wrong thing to do, since this may cause a reused file
descriptor from an‐other  thread  to be closed.  This can occur because the Linux kernel always
releases the file descriptor early in the close operation, freeing it for reuse; the steps that may return
an error, such as flushing data to the filesystem or device, occur only later in the close operation.
```

As such if close() returns error, there is no much Mksquashfs can do, except to abort - print an error, try to delete the output filesystem, and return a error status.
