### ISSUE TITLE
unsquashfs: extract file list ignored if not found

### ISSUE THREAD

**Issue by ptsneves** [plougher/squashfs-tools#187]
If I pass unsquashfs a file to extract and this file does not exist in the file system, I expect unsquashfs to fail. Currently no error nor log is reported.

I looked at the the [code](https://github.com/plougher/squashfs-tools/blob/62a8a93f84b169955054dc086e5024ef4895ad17/squashfs-tools/unsquashfs.c#L2032) and this is where it is ignored if I am correct.

**Comment by plougher** [comment]
This is actually correct behaviour, and it is how "find", "bash" and everything else works, and it is to do with wildcards or globbing.   Filenames with globbing enabled can match on one, multiple or **_no_** files. 

Unsquashfs for instance behaves like "find".  Find recursively descends into a directory hierarchy, matching the given names or pathnames, and performs an action (usually print) on anything that matches, or **_nothing_** if nothing matches.

Some worked examples:

```
phillip@localhost:/mnt/home/phillip/github> find . -path "./squashfs-tools/squashfs-tools/mksquashfs.c"
./squashfs-tools/squashfs-tools/mksquashfs.c
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Here the pathname matches.  Find prints the match, and returns a success exit code.

```
phillip@localhost:/mnt/home/phillip/github> find . -path "./squashfs-tools/squashfs-tools/mksquashfs.*"
./squashfs-tools/squashfs-tools/mksquashfs.1
./squashfs-tools/squashfs-tools/mksquashfs.c
./squashfs-tools/squashfs-tools/mksquashfs.h
./squashfs-tools/squashfs-tools/mksquashfs.o
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Here the pathname matches multiple files.  Each match is printed, and find returns a success exit code.

```
phillip@localhost:/mnt/home/phillip/github> find . -path "./squashfs-tools/squashfs-tools/mksquashf.*"
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Here the pathname doesn't match anything.  **_Nothing_** is printed, and find returns a success exit code.

```
phillip@localhost:/mnt/home/phillip/github> find . -path "./squashfs-tools/squashfs-tools/harry"
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Again the pathname doesn't match anything.  **_Nothing_** is printed, and find returns a success exit code.  Note no wildcards have been used.

The Bash shell works in the same way.  It walks the pathname given, performing **_wildcard expansion_**, replacing the pathname with all the pathnames that match.  These pathnames are then passed to the command to be executed.    Many people *think* its the command which does the wildcard matching, but, this isn't so. 

If Bash **_doesn't_** find a pathname match, it doesn't **_fail_** - it passes the **_unmatched_** pathname to the command.  It is the command which fails when it passes the pathname to an _open()/stat() etc._ system call, which returns error when it can't be resolved.

Again some worked examples:

```
phillip@localhost:/mnt/home/phillip/github> ls -la ./squashfs-tools/squashfs-tools/mksquashfs.c
-rw-r--r-- 1 phillip users 227207 Aug 12 17:26 ./squashfs-tools/squashfs-tools/mksquashfs.c
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Here, there are no wildcards, and Bash passes the pathname unexpanded to the ls command.  The ls command succeeds.

```
phillip@localhost:/mnt/home/phillip/github> ls -la ./squashfs-tools/squashfs-tools/mksquashfs.*
-rw-r--r-- 1 root    root   15543 Aug 12 17:27 ./squashfs-tools/squashfs-tools/mksquashfs.1
-rw-r--r-- 1 phillip users 227207 Aug 12 17:26 ./squashfs-tools/squashfs-tools/mksquashfs.c
-rw-r--r-- 1 phillip users   7294 Aug 10 18:01 ./squashfs-tools/squashfs-tools/mksquashfs.h
-rw-r--r-- 1 phillip users 225152 Aug 12 17:27 ./squashfs-tools/squashfs-tools/mksquashfs.o
phillip@localhost:/mnt/home/phillip/github> echo $?
0
```

Here there are wildcards, and Bash will replace the pathname with the **_four_** matches on the command line.   The ls command is passed these four pathnames, and it succeeds.

```
phillip@localhost:/mnt/home/phillip/github> ls -la ./squashfs-tools/squashfs-tools/mksquashf.*
ls: cannot access './squashfs-tools/squashfs-tools/mksquashf.*': No such file or directory
phillip@localhost:/mnt/home/phillip/github> echo $?
2
```

Here there are also wildcards, which Bash tries to match.  But, there are no matches, and so Bash passes it unexpanded to the ls command.  The ls command passes the pathname to the _stat()_ system call, which returns -ENOENT (no such file or directory).

**Comment by plougher** [comment]
The question you should have asked is ... is there any way in Unsquashfs to disable wildcard/globbing and make it treat filenames as exact matches and fail if they don't exist.

The answer to that question is Yes.  It is called the -missing option.

```
phillip@localhost:/tmp> unsquashfs /tmp/test.sqsh "squashfs-tools/squashfs-tools/mksquashf.*"
Parallel unsquashfs: Using 4 processors
0 inodes (0 blocks) to write

created 0 files
created 3 directories
created 0 symlinks
created 0 devices
created 0 fifos
created 0 sockets
created 0 hardlinks
phillip@localhost:/tmp> echo $?
0
```

Wildcards/globbing are enabled, and Unsquashfs doesn't fail if there are no matches present.

```
phillip@localhost:/tmp> unsquashfs -missing /tmp/test.sqsh "squashfs-tools/squashfs-tools/mksquashf.*"
FATAL ERROR: Extract filename squashfs-tools/squashfs-tools/mksquashf.* can't be resolved
phillip@localhost:/tmp> echo $?
1
```

Failure to resolve will result in Unsquashfs aborting, and it will return an error exit status.

**Comment by ptsneves** [comment]
@plougher Oh man! What a delightful answer! Thank you very much for your time. Naturally you are right and I got a good brush up on the expansion details. Especially the bash part, I knew it was the shell that expanded it but never thought of the consequences in some of the cases.

Big cheers! The best answer I ever got on an issue!

**Comment by plougher** [comment]
@ptsneves Thanks for your reply :-)  I never like telling people they're wrong and I'm right, because it often comes over as "big headed" or arrogant or obnoxious (take your pick).   This is why I go through the details myself (to double check), and I try to explain what is going on in the answer.  I always hope that makes the "I'm right, you're wrong" message easier to swallow.
