### ISSUE TITLE
Feature request: create directories for mount points in -one-file-system mode

### ISSUE THREAD

**Issue by brandsimon** [plougher/squashfs-tools#189]
When using `-one-file-system`, mksquashfs does not create the directories containing those files. Every mount point could be created via specifying `-p "/mnt/point d 0700 0 0"`, but then the script needs to look for all mount points and could also just use `-e` for every mount point.
I expected mksquashfs to create those directories, so I could just replace the files with the created image.
I don't think including these directories will break backwards compatibility, but another option could also be used.

**Comment by henkye** [comment]
+1
For example rsync works like mentioned above (--one-file-system, -x)

**Comment by plougher** [comment]
I will have a look and see what other utilities do in this case.   I suspect they will create the directories like rsync, and so the current Mksquashfs behaviour is probably wrong ....

This feature came as a "pull request", but the implementation was rather inefficient.  I rewrote it but retained the behaviour.

**Comment by brandsimon** [comment]
@plougher Thank you very much for your work and time!
