### ISSUE TITLE
looking for version 2.9

### ISSUE THREAD

**Issue by KacperSJS222** [plougher/squashfs-tools#193]
Hi, I have a file created with version 2.9 but that version doesn't seem to exist anywhere neither on github or sourceforge.

Binwalk confirms that this file was created with version 2.9:
![image](https://user-images.githubusercontent.com/23265905/175163484-9e3e662e-1379-476b-b1dc-e655e218390b.png)

I've tried with 3.1 but it says it doesn't support 2.9:
![image](https://user-images.githubusercontent.com/23265905/175164409-6603a940-1fae-47b3-909f-09ae36cd2fad.png)

So I've also tried with 3.2 but that doesn't work either:
![image](https://user-images.githubusercontent.com/23265905/175164703-f5d66c62-ff13-44ef-8288-1a5decb664df.png)

Is there anything I can do to unpack that file ?

**Comment by plougher** [comment]
Filesystem version 2.9 indicates the filesystem has been created using modified tools (i.e. not official).   This is typically done by third parties to prevent the filesystem being unpacked with the standard tools.

You could check the vendor website to see if they have released the modified source code (unlikely).

Unfortunately there is nothing I can do here, as they are using modified versions of my tools.
