### ISSUE TITLE
[Recovery help] Recover partial squashfs file

### ISSUE THREAD

**Issue by sudipghimire533** [plougher/squashfs-tools#196]
After I created a squashfs of my directory and copied with `cp` command, I am not sure weather the copy was complete or not. ( it seems like it was not orifinal file was 12GB this one is 11.2GB ). Foolish of me, I wiped the original disk without any second though and now when I try to recover the squashfs it says:
```
└──╼ $file filesystem.squashfs 
filesystem.squashfs: Squashfs filesystem, little endian, version 4.0, zlib compressed, 11993237712 bytes, 1070151 inodes, blocksize: 1048576 bytes, created: Sat Aug  6 04:56:03 2022
```

```
└──╼ $unsquashfs -info filesystem.squashfs 
Read on filesystem failed because EOF
File system corruption detected
FATAL ERROR:failed to read file system tables
```

Is there a way I could extract at-least what is already there? It would be helpful to get my some ( now I am sure I cannot get all of it ) of my data back

**Comment by plougher** [comment]
> I am not sure weather the copy was complete or not. ( it seems like it was not orifinal file was 12GB this one is 11.2GB )

If that is the case then you've lost 800 Mbytes - which is unrecoverable from.

However, your above file command reports the filesystem size (stored in the superblock) as 11993237712 bytes, or 11.17 GB ...

So, if the file size is 11.2 GB, that is entirely correct, and the file is not truncated.

Your next step should be to run "stat filesystem.squashfs", and paste the output here.  Which will allow the actual file size to be compared with the filesystem size stored in the superblock.

**Comment by sudipghimire533** [comment]
output of `stat filesystem.squashfs`:
```
└──╼ $stat filesystem.squashfs 
  File: filesystem.squashfs
  Size: 10121369600	Blocks: 19768304   IO Block: 4096   regular file
Device: 27h/39d	Inode: 372113      Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   sudip)   Gid: ( 1001/   sudip)
Access: 2022-08-07 10:12:57.000000000 +0545
Modify: 2022-08-06 10:41:04.000000000 +0545
Change: 2022-08-07 10:13:16.342244904 +0545
 Birth: 2022-08-07 10:12:57.772245482 +0545
 ```
 
 output of `unsquashfa -s filesystem.squashfs`
 ```
└──╼ $unsquashfs -s filesystem.squashfs 
Found a valid SQUASHFS 4:0 superblock on filesystem.squashfs.
Creation or last append time Sat Aug  6 10:41:03 2022
Filesystem size 11993237712 bytes (11712146.20 Kbytes / 11437.64 Mbytes)
Compression gzip
Block size 1048576
Filesystem is exportable via NFS
Inodes are compressed
Data is compressed
Uids/Gids (Id table) are compressed
Fragments are compressed
Always-use-fragments option is specified
Xattrs are compressed
Duplicates are not removed
Number of fragments 15447
Number of inodes 1070151
Number of ids 45
```

**Comment by plougher** [comment]
Also you should run "unsquashfs -version" and paste the output here.  The error message you report indicates that the Unsquashfs you're using is an older version.

Also what happens if you try to mount the filesystem as superuser (root).  The output from

sudo mount -t squashfs filesystem.squashfs /mnt -o loop

Would be useful ....  Does it succeed, and if it doesn't, what is the output from the "dmesg" command.

From what you have said, the filesystem is likely to be unrecoverable, but the above questions will give more insight into the issue.

**Comment by sudipghimire533** [comment]
```
└──╼ $unsquashfs -version
unsquashfs version 4.4 (2019/08/29)
copyright (C) 2019 Phillip Lougher <phillip@squashfs.org.uk>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
```
---
```
└──╼ $sudo mount -t squashfs filesystem.squashfs /mnt/testing/squashfs/ -o loop
mount: /mnt/testing/squashfs: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
```
---
```
└──╼ $sudo dmesg | tail
[   25.918627] IPv6: ADDRCONF(NETDEV_CHANGE): wlp4s0: link becomes ready
[   37.463383] pcieport 0000:00:01.1: Data Link Layer Link Active not set in 1000 msec
[  612.399421] nouveau 0000:01:00.0: DRM: Dropped ACPI reprobe event due to RPM error: -22
[  613.427396] acer_wmi: Unknown function number - 8 - 1
[ 1594.382687] pcieport 0000:00:01.1: Data Link Layer Link Active not set in 1000 msec
[ 7128.441210] loop: module loaded
[ 7128.441472] loop0: detected capacity change from 0 to 19768300
[ 7128.492041] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[ 7137.442178] loop0: detected capacity change from 0 to 19768300
[ 7192.691509] loop0: detected capacity change from 0 to 19768300
```

**Comment by plougher** [comment]
Ok, thanks for the extra information.  My last post crossed with you last post.

You have 9.43 GB left of a file originally 11.17 GB, which means 1.74 GB is missing, or about 15%.

That 1.74 GB will include all the filesystem metadata.  Without that metadata, all you have is a series of compressed data blocks with no information how to decompress  them or reconstitute them back into files.

Unfortunately, this is not recoverable.

**Comment by sudipghimire533** [comment]
Can I not even extract what's in the beginning block?

**Comment by plougher** [comment]
No.   It is the same as having a  kit of parts (car, airplane etc.) without the instructions to put them together.  A car may have more than 20,000 parts, and an airplane much more.

In your case, you have about 20,000 - 30,000 blocks, containing about 1 million files.  You have no information how to put them together.

To explain the pointlessness here:

Your first block may or may not be compressed.  In both cases you have no information about how big the block is.  If you do manage to work that out and decode it, then you have to do that for the next block, and the next block, and so on.

If you have done that, you will have a sequence of blocks.  This sequence of blocks may be one large file, or it may be a sequence of small files.   Each block will need to be examined to see if it is the start of a file, or part of a file, and so on for every block.  To complicate matters, multiple small files are packed together in blocks, and these will have to examined and split.

If you want to try and do that, then feel free.

I have been patient and I have spent my time explaining the situation to you.   There is nothing more to add here.  I have no liability for loss or corruption of Squashfs filesystems.
