### ISSUE TITLE
mksquashfs4.2 needed in jammy jellyfish

### ISSUE THREAD

**Issue by menash134** [plougher/squashfs-tools#208]
Hi All

I just updated to the jammy jellyfish (ubuntu 22.04), mksquashfs is now version 4.5.
 I need to go to back mksquashfs4 (version 4.2) to create a image from my old project. How shall I do it?
What should I do to install it?

**Comment by plougher** [comment]
Mksquashfs version 4.5 produces exactly the same images as Mksquashfs version 4.2, and so you don't need to do anything.

The source package for Mksquashfs version 4.2 is still available here https://sourceforge.net/projects/squashfs/files/squashfs/squashfs4.2/
