### ISSUE TITLE
'gid' missing from the "command" pseudo definition format in error message

### ISSUE THREAD

**Issue by countingpine** [plougher/squashfs-tools#22]
mksquashfs test.txt test.sfs -p "hi.txt f 444 root echo hi"
    Gid echo invalid uid or unknown user
    Pseudo definitions should be of format
            filename d mode uid gid
            filename m mode uid gid
            filename b mode uid gid major minor
            filename c mode uid gid major minor
            filename f mode uid command

The `gid` parameter is missing from the last line.  And as the error shows, it does indeed try to parse the word after the uid as a gid.

This is from v4.2-git (2013/04/07), but it looks like it is still the same in pseudo.c in the master branch.

https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/pseudo.c#L495

(Also, it would be great to see that list of pseudo definition formats in the help text or manpage.)

**Comment by plougher** [comment]
Pseudo files are documented in the RELEASE-README [here](https://github.com/plougher/squashfs-tools/blob/master/RELEASE-README).

But text fixed and added to the help text too.
