### ISSUE TITLE
Give release files a name ... (please)

### ISSUE THREAD

**Issue by alphons** [plougher/squashfs-tools#227]
as a systembuilder, nameless release files (5.4.1) gives me problems in my build systems
can you (please) prefix the (future) release files with something like 'squashfs-tools-'
so the result is something like squashfs-tools-5.4.1.tar.gz 
when untarring, the name of the directory is perfect, its only the name of the release file.
it makes this project so much more compatible with other packages (gnu etc.)

thanks

**Comment by plougher** [comment]
The problem will appear to be that Github is using the name of the tag "4.5.1" to do the tar file naming.   But it is using the name of the repository (squashfs-tools) and adding the release tag (4.5.1) with a joining "-" to name the directory inside it.  I don't see where else it is getting the directory name.

If I name the tag "squashfs-tools-4.6" that should fix the tar file naming issue.  But will Github be intelligent enough to just name the directory inside squashfs-tools-4.6, or do something stupid like squashfs-tools-squashfs-tools-4.6.  Only one way to find out ...

**Comment by plougher** [comment]
Bingo - now I've got a complaint that the tagging has changed https://github.com/plougher/squashfs-tools/issues/232

The fact the tar file hasn't got "squashfs-tools"  in it, and requires junk is added to the tag is evidently a Gihub issue.

Please go and complain to them.

**Comment by plougher** [comment]
Two tags, two tarballs, same git commit.

https://github.com/plougher/squashfs-tools/archive/refs/tags/4.6.tar.gz

https://github.com/plougher/squashfs-tools/archive/refs/tags/squashfs-tools-4.6.tar.gz

**Comment by kloczek** [comment]
> as a systembuilder, nameless release files (5.4.1) gives me problems in my build systems
> can you (please) prefix the (future) release files with something like 'squashfs-tools-'
> so the result is something like squashfs-tools-5.4.1.tar.gz

With tag like `5.4.1` you can download https://github.com/plougher/squashfs-tools/}/archive//5.4.1/squashfs-tools-5.4.1.tar,gz and in that tar ball base direcrory will be `<repo-name>-<git.tag>/`.
github allows download files like `https://github.com/account/repo-name/}/archive//<tag>/<any_name_you_want>.tar,gz`
Now with new tag `'squashfs-tools-4.6` inside https://github.com/plougher/squashfs-tools/}/archive//squashfs-tools--5.6/squashfs-tools-5.6.tar,gz  base direcory is `quashfs-tools-quashfs-tools-4.6/`.

May I ask at least add second tag on the same hash just '4.6` or go back to old taging convention? 🤔

**Comment by kloczek** [comment]
OK I see that second tag has been added.
Howwever IMO using tags like `<some-name>-<version>` does not make any sense because how github mechanick of autogenerated tar balls from git tags is working.
