### ISSUE TITLE
4.6: change in tagging convention

### ISSUE THREAD

**Issue by kloczek** [plougher/squashfs-tools#232]
Is it any reson why tagging converison has been changed from `<version.with.dots>` to `squashfs-tools-<version.with.dots>`? 🤔

**Comment by plougher** [comment]
Yes issue https://github.com/plougher/squashfs-tools/issues/227

Is too much to ask that I don't get constant conflicting requests and issues.

Just once could I not have someone complaining after a release.

**Comment by plougher** [comment]
Two tags, two tarballs, same git commit.

https://github.com/plougher/squashfs-tools/archive/refs/tags/4.6.tar.gz

https://github.com/plougher/squashfs-tools/archive/refs/tags/squashfs-tools-4.6.tar.gz

**Comment by alphons** [comment]
Your the best !!
