### ISSUE TITLE
Core dump when packing files with ACLs

### ISSUE THREAD

**Issue by nl6720** [plougher/squashfs-tools#234]
`mksquashfs` (from [Arch Linux package squashfs-tools 4.6-1](https://archlinux.org/packages/testing/x86_64/squashfs-tools/)) core dumps when packing files with POSIX ACLs.

For example:
```
$ mkdir /tmp/sfstest /tmp/sfstest/test1
$ setfacl -m 'g:wheel:r' /tmp/sfstest/test1
$ setfacl -d -m 'g:wheel:r' /tmp/sfstest/test1
$ mksquashfs /tmp/sfstest /tmp/test.sfs -noappend
```
```
Creating 4.0 filesystem on /tmp/test.sfs, block size 131072.
Unrecognised xattr prefix �m�ÔU
free(): invalid pointer
```

The unrecognised xattr prefix changes each time.

Previously (squashfs-tools 4.5.1), it simply complained, but ran successfully.
```
Unrecognised xattr prefix system.posix_acl_default
Unrecognised xattr prefix system.posix_acl_access
```

See also Arch Linux issue [FS#77914](https://bugs.archlinux.org/task/77914).

**Comment by eworm-de** [comment]
The first bad commit is 744ca24fd680eb0535b251e801be10195d2ffcfb...
