### ISSUE TITLE
Possible to make only certain files uncompressed on a squash archive?

### ISSUE THREAD

**Issue by i30817** [plougher/squashfs-tools#24]
I'm thinking of files which already have specialized compression, where further compression would just add latency, but which are 'logically' part of a set which go into a squash partition. 

Can append do this, or am i better asking for a special knob to do this?

If not, I've often thought that the exclusion file can be extended control some settings per file (if extended beyond 'exclusion' ofc). This could be a usecase.

**Comment by plougher** [comment]
You may be glad to know this is a feature already supported in Mksquashfs.  Sadly, for various reasons, I didn't document it in the last release of Squashfs-tools, and so it is a "hidden feature", available for use but not documented.

If you're aware of the "find" utility, then the following description and use-cases should be fairly obvious, as this feature can thought of as a mini-find within Mksquashfs.

Find evaluates a series of "tests" and if these return TRUE, executes an action.

So this command "find dir -type f -print" prints all the files within dir which are regular files.

If you know find, you'll also know there are a lot of tests which can be performed on files, wildcard name matching, filesize, type, etc., and these can be combined with logical operators (and, or, not) to build up more complex match expressions.

So what about Mksquashfs?  This feature which I called (perhaps unsurprisingly) actions, evaluates a series of test operators and then performs an action, if they return TRUE.

One of the actions you'll be interested in is called "uncompressed", this tells Mksquashfs not to compress the files which the test operators return TRUE.

Like in find, there exists quite a number of test operators, and they can be combined with logical operators (&&. ||, !).

So this command

mksquashfs zzz zzz.sqsh -action "uncompressed@name(*.c)"

Will make all files which match the wildcard "*.c" uncompressed.  It obviously works for any wildcard.

Likewise, there is a file-size test operator called unsurprisingly "filesize".

So

mksquashfs zzz zzz.sqsh -action "uncompressed@filesize(4096)"

will make all files exactly 4096 bytes in length uncompressed.

Like in find, you use
       +n     for greater than n,
       -n     for less than n,
       n      for exactly n.

So

mksquashfs zzz zzz.sqsh -action "uncompressed@filesize(-4096)

will match filesizes less than 4096.

Test operators can obviously be combined.

mksquashfs zzz zzz.sqsh -action "uncompressed@name(*.c) && filesize(-4096)"

will match on files with names "*.c" and are less than 4096 bytes in size.

There are a lot of other tests and actions.  If you're interested, look at the end of action.c in the source code.

One day I may get around to documenting this.

**Comment by i30817** [comment]
Thank you.

**Comment by nigels-com** [comment]
Good to know.  Thanks!

**Comment by plougher** [comment]
Closing as this issue is already supported.
