### ISSUE TITLE
[Question] How to calculate total file size?

### ISSUE THREAD

**Issue by jrruethe** [plougher/squashfs-tools#26]
Hello,

I'm trying to determine how to calculate the total size of a squashfs file using only information in the superblock, with the goal of obtaining the same number given by `ls`.

What I have done is created a squashfs file where `ls` reports  `153485312` bytes. Using both binwalk and a hex editor (to view the bytes_used field of the superblock), I get a size of `153483846`, a difference of `1466` bytes. (I also tried a second squashfs file and got different results for the size difference, 1935). I can't seem to figure out how to calculate the remainder.

Said another way, imagine that I took two squashfs files and concatenated them together. Reading the superblock of the first file is easy, since it is at the very beginning. How would I calculate the starting location of the superblock for the second file?

```
cat a.sfs > output.bin
cat b.sfs >> output.bin
binwalk output.bin
```

Thank you for your help and time!

**Comment by Dr-Emann** [comment]
By default, squashfs archives are rounded up to the nearest 4k (unless the [`nopad`](https://github.com/plougher/squashfs-tools/blob/9c1db6d13a51a2e009f0027ef336ce03624eac0d/RELEASE-README#L126) option is passed). This explains the difference in size.

If concatenating multiple squashfs archives, either create the archives with `-nopad` (or trim off the extra bytes left by padding), or look for the next archive at `(used_bytes + 4095) / 4096 * 4096`

**Comment by jrruethe** [comment]
Hey! That is awesome, and answers all my questions! Thank you for your time

**Comment by jackjack272** [comment]
can you explain how you get the length in the first place? i dident find any good articles. and Dr-emann dident include the offsets in his article so i dont know if the bytes are 4 in length or of variable legth    

his article: https://dr-emann.github.io/squashfs/squashfs.html

**Comment by Dr-Emann** [comment]
The first section of a squashfs archive is always [the superblock](https://dr-emann.github.io/squashfs/squashfs.html#_the_superblock)

Fields in the superblock are located one after another, and their size is determined by their type (u32 -> unsigned 32 bit integer: 4 bytes, i16 -> signed 16 bit integer: 2 bytes, etc)

The bytes_used field is located after five `u32`s, six `u16`s, and one `u64`, so it should be located at offset `5 * 4 + 6 * 2 + 1 * 8` or offset `40` (or `0x28`), and it is itself a `u64`, so if you read a little endian 64 bit unsigned integer from offset `0x28`, that should give you the length of the squashfs archive.

**Comment by Dr-Emann** [comment]
And to avoid taking too much credit, I don't think it's accurate to call that "my article", that document was created almost entirely by @AgentD (though it is based on [my original attempt to document the squashfs format](https://dr-emann.github.io/squashfs/)).

**Comment by jackjack272** [comment]
thank you the most for explaining it. 

Im very new to this, so i really appreciate the spoon feeding.
