### ISSUE TITLE
Failed to read directory in rare cases of appending with -root-becomes

### ISSUE THREAD

**Issue by Starterware** [plougher/squashfs-tools#262]
Hi, 

I fell on a rare issue with the mksquashfs command when appending a directory to a squashfs file with -root-becomes. The mksquashfs command succeeds but when mounting or running the unsquashfs command, it cannot read the newly created subfolder.

In attachment, there is one of the cases that causes the issue: it is a directory with multiple directories and multiple empty files.

To reproduce:
./mksquashfs rootfolder output.sqsh -noappend 
./mksquashfs <anydir> output.sqsh -root-becomes subfolder
./unsquashfs -ll output.sqsh

> dir_scan: failed to read directory squashfs-root/subfolder, skipping

Interesting observations:

* Adding/Removing one char from any folder or file makes the issue disappear
* Renaming any folder/file with the same amount of chars result in the same issue
* It only happens when using option -root-becomes. No issue when moving the content of rootfolder to rootfolder/subfolder and then not using -root-becomes. No issue either when not appending (create the wanted final folder and then mksquashfs -noappend).

I simply wanted to report the issue. I’ll try to find some time to continue my investigation but not being familiar with the code makes it quite complex.

[rootfolder.zip](https://github.com/plougher/squashfs-tools/files/12446122/rootfolder.zip)

**Comment by plougher** [comment]
The fact adding or removing a char "fixes" the problem whereas renaming with the same amount of chars does not, suggests a "one-off" bug.    I'll try and reproduce it and find the problem tomorrow (Monday).

In your "to reproduce" steps, you have the source directory in the second Mksquashfs missing.

```
> To reproduce:
> ./mksquashfs rootfolder output.sqsh -noappend
> ./mksquashfs output.sqsh -root-becomes subfolder

No source directory

> ./unsquashfs -ll output.sqsh
```

**Comment by plougher** [comment]
I have downloaded the zip file and tried to reproduce the issue using random directories as the source in the second mksquashfs command.   So far I have been unable to reproduce it.

Does reproducing it rely on a specific source directory specified in the second mksquashfs command?

Also you don't mention what Linux distro you're running, or where the Squashfs-tools came from or their version.

Have you reproduced the issue on the latest version from Github, or is this on an older version provided by the distro?

Knowing this will aid in both reproducing the issue and knowing the cause.

**Comment by plougher** [comment]
OK.  I have now managed to reproduce the issue.   Your ZIP file appears to have a top level ___MACOS directory with a sub-directory called rootfolder, and a top-level directory also called rootfolder.   Only running Mksquashfs on the top-level rootfolder reproduces the issue.  The double presence of rootfolder is confusing.

I will update when I get any progress.

**Comment by Starterware** [comment]
Thanks for looking into it! 

My excuses for the troubles with the zip and the command (forgot that markdown removes tags, there was one in the command saying any-source).

For the issue, I reproduced it on the latest version and on the 4.3 version.
