### ISSUE TITLE
Conventional extension for squashfs files: .sqfs, .sqsh, .squashfs etc ?

### ISSUE THREAD

**Issue by prioux** [plougher/squashfs-tools#265]
Hi there.

Not sure if this has already been covered or discussed in the past, but I'd like to know if there is an established, accepted convention for the extension we should use for squashfs filesystems.

I can see in the documentation (right here on GitHub) that this is not completely consistent. There are examples using both `.sqsh` and `.sqfs`. I've also seen out there `.squashfs` and `.sqs`.

Personally, I dislike `.sqsh`, because the letters `sh` are strongly associated in my mind to the word **shell**. A file named `.sqsh` seems to be a script for some sort of SQ shell. Consider how we immediately think of shells when we see files named `init.bash`, `init.tcsh`, `init.ksh`, `init.sh`, etc etc.

I like `.sqfs` however, it's pretty clear with the letters `fs` that we're talking about a filesystem.

If that's OK with the developers, I volunteer to make a PR to update all the documentation here and make sure all examples use `.sqfs` as an extension (my preference, as I said) or whatever else people prefer.

**Comment by prioux** [comment]
Sorry if this is a duplicate. Also, if a convention already exists, we could update the Wikipedia page's side bar and add the extension name there.

**Comment by Dr-Emann** [comment]
See also #259

**Comment by prioux** [comment]
All good. Thanks!
