### ISSUE TITLE
Investigate Zstandard compressor

### ISSUE THREAD

**Issue by probonopd** [plougher/squashfs-tools#27]
Would this be a good candidate for squashfs compression?
https://en.wikipedia.org/wiki/Zstandard

**Comment by terrelln** [comment]
The decompressor is merged into the 4.14 kernel, and supported by SquashFUSE. The patch for squashfs-tools is ready, but not merged yet.

**Comment by terrelln** [comment]
6113361 adds support for creating zstd compressed images, which can be consumed by the 4.14 kernel and squashFUSE.
