### ISSUE TITLE
INODE_HASH always returns 2 with a weka network filesystem

### ISSUE THREAD

**Issue by jbd** [plougher/squashfs-tools#281]
Hello,

[this replaces https://github.com/plougher/squashfs-tools/issues/280]

I'm running a network file system called weka.io (https://www.weka.io/). I guess it is by design on their side, but inode number seems to always end with 2 (0b0000000000000010). 

```
[...]
ino: 7506914778566754306 hash: 2
ino: 10817625003453251586 hash: 2
ino: 9911183293093249026 hash: 2
ino: 5120815407798419458 hash: 2
ino: 158886764295815170 hash: 2
ino: 9889276914285150210 hash: 2
ino: 13942752167935016962 hash: 2
ino: 9358342502787317762 hash: 2
ino: 14759486187258183682 hash: 2
ino: 9016589265391976450 hash: 2
ino: 7912710082708176898 hash: 2
ino: 4934652761806012418 hash: 2
ino: 4731200428047532034 hash: 2
ino: 692080221120102402 hash: 2
ino: 2857600357847728130 hash: 2
ino: 9086834014424858626 hash: 2
ino: 4018635512649023490 hash: 2
ino: 8978163501103054850 hash: 2
ino: 889286832005447682 hash: 2
ino: 15444634868125007874 hash: 2
ino: 12555394296762531842 hash: 2
ino: 5723500116489863170 hash: 2
ino: 17305642794461822978 hash: 2
ino: 5245136825359728642 hash: 2
ino: 10162592242947784706 hash: 2
ino: 7543904611772268546 hash: 2
ino: 17082912803229138946 hash: 2
[...]
```

Since the INODE_HASH is just `st_ino & 65534`, the resulting hash is always 2. The side effect is that lookup_inode3 function rapidly becomes very slow as the number of files increase. 

I tell my users to use -no-hardlinks option as a workaround to prevent this lookup.

I don't have any suggestions for a real correction sorry.

Thank you for this amazing tool and its maintenance over the years.

Jean-Baptiste

**Comment by plougher** [comment]
Testing the above commit with problematic inode numbers shows it should fix this issue.

**Comment by jbd** [comment]
It's working perfectly, thank you !

I'm closing the issue.
