### ISSUE TITLE
pseudofile defs builds non-deterministic squashfs images

### ISSUE THREAD

**Issue by lalten** [plougher/squashfs-tools#288]
I'm using mksquashfs in https://github.com/lalten/rules_appimage in a probably pretty non-standard way.

The use case for rules_appimage (a Bazel ruleset) is that a large number of files and symlinks needs to be packaged into a squashfs image, but the structure of the existing files is different from the required structure inside the image.

It is possible to copy all files to a directory, giving them the desired structure, and then running mksquashfs on that. However all the copy operations can be expensive.

What I'm doing instead is describing the desired Squashfs structure with a pseudofile definition file by adding `path/to/file f 777 0 0 cat path/to/file` (etc) lines.

This leads to non-deterministic squashfs builds. Below is a demonstration

```sh
#!/bin/bash

# Generate a fake pseudo file definitions file from /usr/local/share
# and create a squashfs image from it.
# Running this multiple times leads to changing squashfs image hashes.

set -eu

pf=/tmp/pf.txt
rm -f $pf
echo "/usr d 777 0 0" >>$pf
echo "/usr/local d 777 0 0" >>$pf
while IFS= read -r -d '' dir; do
    echo "\"$dir\" d 777 0 0" >>$pf
done < <(find /usr/local/share -type d -print0)
while IFS= read -r -d '' file; do
    echo "\"$file\" f 777 0 0 cat \"$file\"" >>$pf
done < <(find /usr/local/share -type f -print0)

emptydir="$(mktemp -d)"
sqfs=/tmp/test.sqfs
rm -f $sqfs

set -x
mksquashfs $emptydir $sqfs -pf $pf -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0

sha256sum $pf $sqfs
```
Running it:
```
❯ /tmp/make_test_squashfs.sh
+ mksquashfs /tmp/tmp.lScOfdbiwB /tmp/test.sqfs -pf /tmp/pf.txt -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0
+ sha256sum /tmp/pf.txt /tmp/test.sqfs
8e2f570b6dc8a29c3ee813c735a9173b3c9797616e6ee61a786bf082712852fb  /tmp/pf.txt
358da502e64f84abca7a90592dd710380ab0f7f7eca35b6d46a8a3422a696e4b  /tmp/test.sqfs

❯ /tmp/make_test_squashfs.sh
+ mksquashfs /tmp/tmp.x5xs8ygD6T /tmp/test.sqfs -pf /tmp/pf.txt -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0
+ sha256sum /tmp/pf.txt /tmp/test.sqfs
8e2f570b6dc8a29c3ee813c735a9173b3c9797616e6ee61a786bf082712852fb  /tmp/pf.txt
222a9eed936250d3eebb923e356409652b68d1f8aad16ef02221f49f7888cb64  /tmp/test.sqfs
```

I'm assuming this is due to nondeterminstic threading of the `cat` commands leading to nondeterminstic order inside the image?

Is there a way to make this work in a deterministic way?

**Comment by plougher** [comment]
The reason why you're getting different checksums is because of different timestamps.   Each `d` and `f` pseudo file definition uses "now" or current time for its timestamp.

On the mksquashfs command line, `-root-time` makes the root inode timestamp 0, and `-mkfs-time` makes the filesystem creation time 0, but nothing sets the pseudo file timestamps to 0.

One way of fixing this is to add `-all-time 0` to the mksquashfs command line, which will force all timestamps to 0.

```
mksquashfs $emptydir $sqfs -pf $pf -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0 -all-time 0
```

This will of course give everything in the Squashfs image a timestamp of 0.

Another way which only affects the pseudo file timestamps is to use the `extended` pseudo file definitions `D` and `F` which take a timestamp.

The amended script which does that is:

```
#!/bin/bash

# Generate a fake pseudo file definitions file from /usr/local/share
# and create a squashfs image from it.
# Running this multiple times leads to changing squashfs image hashes.

set -eu

pf=/tmp/pf.txt
rm -f $pf
echo "/usr D 0 777 0 0" >>$pf
echo "/usr/local D 0 777 0 0" >>$pf
while IFS= read -r -d '' dir; do
    echo "\"$dir\" D 0 777 0 0" >>$pf
done < <(find /usr/local/share -type d -print0)
while IFS= read -r -d '' file; do
    echo "\"$file\" F 0 777 0 0 cat \"$file\"" >>$pf
done < <(find /usr/local/share -type f -print0)

emptydir="$(mktemp -d)"
sqfs=/tmp/test.sqfs
rm -f $sqfs

set -x
mksquashfs $emptydir $sqfs -pf $pf -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0

sha256sum $pf $sqfs
```

Running it

```
phillip@phoenix:/tmp$ ./test2.sh; ./test2.sh
+ mksquashfs /tmp/tmp.v0oT0gmvzt /tmp/test.sqfs -pf /tmp/pf.txt -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0
+ sha256sum /tmp/pf.txt /tmp/test.sqfs
d5fb08f5ccd79ef4b5b0bd10d591a6f1f3d53978137ea2abce7cbf85efbd1d0e  /tmp/pf.txt
a15e5f59bd6232c58b4690dc9d05bf149738014dbd45160f175dcf298867785d  /tmp/test.sqfs
+ mksquashfs /tmp/tmp.PYsGU4N9Vv /tmp/test.sqfs -pf /tmp/pf.txt -exit-on-error -quiet -no-progress -all-root -reproducible -mkfs-time 0 -root-time 0
+ sha256sum /tmp/pf.txt /tmp/test.sqfs
d5fb08f5ccd79ef4b5b0bd10d591a6f1f3d53978137ea2abce7cbf85efbd1d0e  /tmp/pf.txt
a15e5f59bd6232c58b4690dc9d05bf149738014dbd45160f175dcf298867785d  /tmp/test.sqfs
```

**Comment by lalten** [comment]
Oh this is great, thank you very much @plougher! I will fix my ruleset to correctly handle timestamps.
Thank you for mksquashfs, it is such a good tool.
