### ISSUE TITLE
squashgs operation not supported 

### ISSUE THREAD

**Issue by midobona** [plougher/squashfs-tools#31]
I am using ubuntu server 14.04.1 and i want edit filesystem.squashfs  after installed squashfs-tools and unsquashfs and edit filesystem and  mksquashfs and build iso i get this error
  `base-installer: info: Using squashfs support for /cdrom/install/filesystem.squashfs anna-install: Installing squashfs-modules anna[21857]: DEBUG: resolver (kernel-image-4.2.0-16-generic-di): package doesn't exist (ignored) anna[21857]: DEBUG: retrieving squashfs-modules-4.2.0-16-generic-di 4.2.0-16.19 kernel: [44.008353] squashfs: version 4.0 (2009/01/31) Phillip Lougher main-menu[3537]: (process:21801): getfattr: .: Operation not supported main-menu[3537]: (process:21801): getfattr: ./bin: Operation not supported main-menu[3537]: (process:21801): getfattr: ./bin/bunzip2: Operation not supported main-menu[3537]: (process:21801): getfattr: ./bin/bzcat: Operation not supported main-menu[3537]: (process:21801): getfattr: ./bin/bzcmp: Operation not supported`  
-- | --
 i think this error becouse kernel version not equal squashfs-tools  is this right ?  and i want install right package squashfs-tools support kernel ubuntu-server 14.04.1  and sorry if my english is bad

**Comment by plougher** [comment]
You seem to have a miss-match between the kernel and the user-space, or the user-space is corrupted in some way.  Without any more information it is impossible to go any further.
