### ISSUE TITLE
mksquashfs's / folder's default permissions is 777 if multiple include directories are specified

### ISSUE THREAD

**Issue by n3rdopolis** [plougher/squashfs-tools#33]
Hi

It seems that when you specify multiple directories to be included, that squashfs-root's / permissions is 777. Although Squashfs is read only, where usually it won't matter, If the squashfs is copied exactly with an installer like calamares, this will mean anyone can create new folders or files in the installed system's / 

How to replicate: Create my folders, and the filesystems. one folder with 777 permissions. One with 755. and the three file systems. one with the 777 folder, one with the 755 folder, and one with both
```
$ mkdir 777
$ chmod 777 777
$ mkdir 755
$ chmod 755 755
$ mksquashfs 777 777 &>/dev/null
$ mksquashfs 755 755 &>/dev/null
$ mksquashfs 755 777 777755 &>/dev/null
$ mksquashfs 777 777.fs &>/dev/null
$ mksquashfs 755 755.fs &>/dev/null
$ mksquashfs 755 777 777755.fs &>/dev/null
```

The 777.fs's root permissions is 777, but this is expected
```
$ unsquashfs -ll 777.fs |grep root
drwxrwxrwx me/me     3 2017-11-10 07:45 squashfs-root
```

The 755.fs's root permissions is 755, as expected
```
$ unsquashfs -ll 755.fs |grep root
drwxr-xr-x me/me     3 2017-11-10 07:45 squashfs-root
```

The one with the two folders included, the root fs's permissions is 777
```
$ unsquashfs -ll 777755.fs |grep root
drwxrwxrwx me/me    37 2017-11-10 07:46 squashfs-root
drwxr-xr-x me/me     3 2017-11-10 07:45 squashfs-root/755
drwxrwxrwx me/me     3 2017-11-10 07:45 squashfs-root/777
```

This as of now, can be worked around, by appending the empty folder with the desired permissions for / 
```
$ mksquashfs 755 777755.fs &>/dev/null
$ unsquashfs -ll 777755.fs |grep root
drwxr-xr-x me/me    37 2017-11-10 07:45 squashfs-root
drwxr-xr-x me/me     3 2017-11-10 07:45 squashfs-root/755
drwxrwxrwx me/me     3 2017-11-10 07:45 squashfs-root/777
```

Thanks

**Comment by plougher** [comment]
The problem here is even though the 0777 setting doesn't work for you, there may be many others where it does.  That 0777 has been there since the beginning in 2002, and to change it now risks breaking many things.

What I have done is add a new "-root-mode" option which allows the mode to be specified on the command line.

That keeps the default 0777 and hopefully keeps everyone else happy who wants something different.
