### ISSUE TITLE
add concise list function

### ISSUE THREAD

**Issue by juanitotc** [plougher/squashfs-tools#34]
Is it possible to add a concise list function "unsquashfs -lc" that only lists files and empty directories in a squashfs archive?

i.e. this:

/usr/local/include/zbuff.h
/usr/local/include/zdict.h
/usr/local/include/zstd.h
/usr/local/include/zstd_errors.h
/usr/local/lib/pkgconfig/libzstd.pc

instead of this:

Parallel unsquashfs: Using 4 processors
5 inodes (29 blocks) to write

squashfs-root
squashfs-root/usr
squashfs-root/usr/local
squashfs-root/usr/local/include
squashfs-root/usr/local/include/zbuff.h
squashfs-root/usr/local/include/zdict.h
squashfs-root/usr/local/include/zstd.h
squashfs-root/usr/local/include/zstd_errors.h
squashfs-root/usr/local/lib
squashfs-root/usr/local/lib/pkgconfig
squashfs-root/usr/local/lib/pkgconfig/libzstd.pc

**Comment by Dr-Emann** [comment]
You can get one (small) part of this by passing `-d ''`, which removes the squashfs-root prefix to all the paths.

Unfortunately, the lines about being parallel/info about block count are written to stdout, so it's not possible to just pipe stderr to null to remove them.

As for not displaying parent directories separately, I think it's unlikely to be implemented. The `-l` option goes through the same code paths as extraction, skipping the actual creation of files/directories. Implementing this would require some sort of look-ahead to check if the current directory is empty or not before outputting the path.

However, it's pretty easy to add as a post-processing step (scan through lines, keeping the last visited path. If the current path starts with the previous path, don't output anything, if it does not, output the previous path).

**Comment by Dr-Emann** [comment]
I've opened an issue (#35) about the extra output lines for processor/inode/block count being included in the output

**Comment by juanitotc** [comment]
unsquashfs -l -d ' ' somefile does indeed get rid of the "squashfs-root" - thanks.

**Comment by plougher** [comment]
-l and -llc (with attributes) option added.  This only lists files and empty directories.

To suppress the output of the other lines now will change the default output of the program, something which I don't want to do, as it  may break existing scripts (i.e. those that blindly skip the first couple of lines).

I have added a -q[uiet] option which doesn't print these lines.

As "squashfs-root" can be already removed, without changing existing default output, I have left that as the solution there.

So to get your output you can do

unsquashfs -d "" -q -lc
