### ISSUE TITLE
unsquashfs -l output contains more than paths

### ISSUE THREAD

**Issue by Dr-Emann** [plougher/squashfs-tools#35]
The output of `unsquashfs -l file.squashfs` always starts with several lines which are not paths, e.g.

```
Parallel unsquashfs: Using 2 processors
120 inodes (121 blocks) to write

```

This is bothersome when trying to use the output of `unsquashfs -l` to do anything with the paths contained, e.g.
```bash
# find paths in squashfs which contain a number:
$ unsquashfs -l file.squashfs | grep '[0-9]'
Parallel unsquashfs: Using 2 processors # Unexpected non-path
120 inodes (121 blocks) to write        # Unexpected non-path
squashfs-root/OLD-READMEs/README-2.0
…
```

I propose two possible changes to fix this:

1. Output the 3 output lines to stderr. This allows stdout to contain only the real output
2. Provide a `-q[uiet]` flag (which I assume would imply the `-n[o-progress]` flag), which suppresses the lines from being output.

**Comment by vaeth** [comment]
> 1. Output the 3 output lines to stderr

Using stderr if no error occured violates the unix way: There are tools which consider any output to stderr an error (e.g. cron).

> 2. Provide a -q[uiet] flag (which I assume would imply the -n[o-progress] flag)

A -quiet flag would be useful, but making it imply -n[o-progress] is not only inconsistent with mksquashfs, but it is IMHO also a bad idea to disallow the possibility to display *only* the progress: As for mksquashfs, there might be certain wrapper scripts which want to display exactly this output when unsquashing. However, it is reasonable that -l (perhaps to together with -q) implies -n[o-progress].

**Comment by Dr-Emann** [comment]
I would be fine with a -quiet flag added to both `mksquashfs` and `unsquashfs`.
`-quiet` would suppress the output of everything but the progress bar, and any output explicitly requested (e.g. -info for unsquashfs).

**Comment by plougher** [comment]
New -q[uiet] option added.
