### ISSUE TITLE
major/minor/makedev need <sys/sysmacros.h>

### ISSUE THREAD

**Issue by fefe17** [plougher/squashfs-tools#53]
Need this patch to compile with glibc 2.28:

diff --git a/squashfs-tools/mksquashfs.c b/squashfs-tools/mksquashfs.c
index 75b3577..d338d91 100644
--- a/squashfs-tools/mksquashfs.c
+++ b/squashfs-tools/mksquashfs.c
@@ -60,6 +60,8 @@
 #include <sys/sysinfo.h>
 #endif
 
+#include <sys/sysmacros.h>
+
 #include "squashfs_fs.h"
 #include "squashfs_swap.h"
 #include "mksquashfs.h"
diff --git a/squashfs-tools/unsquashfs.c b/squashfs-tools/unsquashfs.c
index c5e0876..f4b7ea8 100644
--- a/squashfs-tools/unsquashfs.c
+++ b/squashfs-tools/unsquashfs.c
@@ -39,6 +39,8 @@
 #include <limits.h>
 #include <ctype.h>
 
+#include <sys/sysmacros.h>
+
 struct cache *fragment_cache, *data_cache;
 struct queue *to_reader, *to_inflate, *to_writer, *from_writer;
 pthread_t *thread, *inflator_thread;

**Comment by hunger** [comment]
#52 has a patch for this. It would be great to see this applied:-)

**Comment by mattst88** [comment]
Patch was merged. This issue can be closed.
