### ISSUE TITLE
Remount

### ISSUE THREAD

**Issue by orachas** [plougher/squashfs-tools#75]
I would like to be able to append new files to a mounted squashfs archive in such a way that they are immediately visible.

I have found that the only way to achieve immediate visibility (on the latest Oracle/CentOS/RedHat v7) is to use the script below.

Is there a better way? I can't see it from the docs.

    $ cat addsquash 
    #!/bin/sh

    FileSystem='/home/someuser/archive.squash.xz'
    MountPoint='/home/mount'

    mksquashfs "${1}" "${FileSystem}" -comp xz

    until false
    do if umount "${MountPoint}"
       then mount "${FileSystem}" "${MountPoint}" -t squashfs -o loop
            break
       else sleep 1
       fi
    done

**Comment by u6zk6** [comment]
Why don't you use overlayfs instead, mounting the squashfs mount-point as lowerdir?

**Comment by plougher** [comment]
You should never try to append to a mounted Squashfs filesystem.    Overlays should be used in this case.
