### ISSUE TITLE
xattr-related non-determinism ⇒ non-reproducible SquashFS 

### ISSUE THREAD

**Issue by intrigeri** [plougher/squashfs-tools#78]
Hi,

while working on Tails I've seen different machines, all running mksquashfs 4.4, build different SquashFS. I can't reproduce this problem if I pass `-no-xattrs`. https://github.com/plougher/squashfs-tools/pull/39/commits/ad4b8f0aad4c659c1e437ed94897230cbdb9800d fixes this problem for me.

FWIW, here's the binary diff that diffoscope reports:

<pre>
│ ├── live/4.1.squashfs
│ │┄ Format-specific differences are supported for SquashFS filesystems but no file-specific differences were detected; falling back to a binary diff. file(1) reports: Squashfs filesystem, little endian, version 4.0, 324896058 bytes, 31711 inodes, blocksize: 1048576 bytes, created: Mon Dec  2 21:23:35 2019
│ │ @@ -20305996,15 +20305996,15 @@
│ │  135d84b0: 6f00 0000 6c00 0000 1d00 0000 2b00 0000  o...l.......+...
│ │  135d84c0: 3200 0000 6400 0000 0600 0000 0c00 0000  2...d...........
│ │  135d84d0: 6e00 0000 7900 0000 c800 0000 0800 0000  n...y...........
│ │  135d84e0: 7e84 5d13 0000 0000 2680 0200 0a00 6361  ~.].....&.....ca
│ │  135d84f0: 7061 6269 6c69 7479 1400 0000 0100 0002  pability........
│ │  135d8500: 0020 0000 0000 0000 0000 0000 0000 0000  . ..............
│ │  135d8510: 1080 0000 0000 0000 0000 0100 0000 2800  ..............(.
│ │ -135d8520: 0000 e884 5d13 0000 0000 0100 0000 0c00  ....]...........
│ │ +135d8520: 0000 e884 5d13 0000 0000 0100 0000 2b00  ....].........+.
│ │  135d8530: 0000 1085 5d13 0000 0000 0000 0000 0000  ....]...........
│ │  135d8540: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│ │  135d8550: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│ │  135d8560: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│ │  135d8570: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│ │  135d8580: 0000 0000 0000 0000 0000 0000 0000 0000  ................
│ │  135d8590: 0000 0000 0000 0000 0000 0000 0000 0000  ................
</pre>

**Comment by plougher** [comment]
Fixed by commit c570c6188811088b12ffdd9665487a2960c997a0
