### ISSUE TITLE
unsquashfs inode table block not found

### ISSUE THREAD

**Issue by oneptr** [plougher/squashfs-tools#79]
I am trying to unsquash my backup file; the process stops with

**FATAL ERROR:read_inode: inode table block 767631982871 not found**
      
unsquashfs version 4.3 (2014/05/12)                                                                                                                                                                                  

> unsquashfs -s /data/data.squashfs  
Found a valid SQUASHFS 4:0 superblock on /data/data.squashfs.
Creation or last append time Mon Dec  2 15:53:48 2019
Filesystem size 745475970.53 Kbytes (728003.88 Mbytes)
Compression gzip
Block size 131072
Filesystem is exportable via NFS
Inodes are compressed
Data is compressed
Fragments are compressed
Always-use-fragments option is not specified
Xattrs are compressed
Duplicates are removed
Number of fragments 55600
Number of inodes 902036
Number of ids 12
                                                                                                                                                                                                
1. Why does this happen? Is this a bug?

2. Is there a way to get past this error to recover as many files as possible? This is a backup file and I lost the original data. If I can't use this backup file, I'm loosing important data...

**Comment by oneptr** [comment]
Update: I have access to many more files by just mounting the file instead of trying to unsquash the file. HOWEVER, the problem now is that pretty much every file is named incorrectly.
Let me explain: While the file content seems to be correct, the name of the file does not match up; all filenames in a directory are "shifted by 1" with regard to their content; e.g. id dir data contains the files t1.txt, t2.txt and t3.txt, then t1.txt has the content of t3.txt, t2.txt that of t1.txt etc.
To me this is definitely indicative of a software bug within squashfs. At the very least there should be a check with md5 checksums, and squashfs should indicate if a file name does not match its content.
With over 100,000 files in my achieve, having access to the file content, but the names screwed up it not much better than not having them at all!

**Comment by plougher** [comment]
> I am trying to unsquash my backup file; the process stops with
> 
> **FATAL ERROR:read_inode: inode table block 767631982871 not found**
> 
> unsquashfs version 4.3 (2014/05/12)
> 
> > unsquashfs -s /data/data.squashfs
> > Found a valid SQUASHFS 4:0 superblock on /data/data.squashfs.
> > Creation or last append time Mon Dec  2 15:53:48 2019
> > Filesystem size 745475970.53 Kbytes (728003.88 Mbytes)
> > Compression gzip
> > Block size 131072
> > Filesystem is exportable via NFS
> > Inodes are compressed
> > Data is compressed
> > Fragments are compressed
> > Always-use-fragments option is not specified
> > Xattrs are compressed
> > Duplicates are removed
> > Number of fragments 55600
> > Number of inodes 902036
> > Number of ids 12
> 
>     1. Why does this happen? Is this a bug?
> 

No it is not a bug.

This indicates Unsquashfs has detected unrecoverable metadata corruption within the Squashfs image.

>     2. Is there a way to get past this error to recover as many files as possible? This is a backup file and I lost the original data. If I can't use this backup file, I'm loosing important data...

You should always make sure your backup file is correct.  In fact the way you phrase the question, "how can I get Unsquashfs to ignore the error and recover as much as possible" implies you already know the Squashfs image is corrupt.  Anyone else would simply ask why this is error happening.

This smacks largely of you trying to blame Squashfs for your own negligence.

**Comment by plougher** [comment]
> Update: I have access to many more files by just mounting the file instead of trying to unsquash the file. HOWEVER, the problem now is that pretty much every file is named incorrectly.
> Let me explain: While the file content seems to be correct, the name of the file does not match up; all filenames in a directory are "shifted by 1" with regard to their content; e.g. if dir data contains the files t1.txt, t2.txt and t3.txt, then t1.txt has the content of t3.txt, t2.txt that of t1.txt etc.
> To me this is definitely indicative of a software bug within squashfs. At the very least there should be a check with md5 checksums, and squashfs should indicate if a file name does not match its content.
> With over 100,000 files in my achieve, having access to the file content, but the names screwed up it not much better than not having them at all!

The kernel code has less checks on the correctness of that  metadata.  What you are seeing here is the result of that corruption - a wrong index into the directory table.

Nothing here suggests anything more than a corrupted Squashfs image, and a bad attitude.  None of that is my problem/

**Comment by oneptr** [comment]
I'm sorry that my bug report caused such hurt feelings.

I think it is obvious that some metadata in my squashfs file got currupted. The question is why?

It could be that the file got corrupted after being generated, which is not under control of squashfs, or it could be that it was generated incorrectly due to a bug inside of squashfs.

Let's assume the file was corrupted afterwards. In that case it would still be an improvement if there would be some safeguards implemented; like something based on checksums of file contents verified against file name. Or the file itself could be validated against a checksum. 

In general, I think it's the filesystem that is responsible for keeping files correct, but I also think that this case (squashfs) is special, because it is used to store 1000 or millions of other files, in which case a data corruption is especially impactful.

As an analogy, look at file systems: They generally relied an the hard drive to store data correctly and dismissed any responsibility of data corruption as "not my problem". Then came ZFS along, (it does checksums on files) and most people agree that this is one of the better filesystems (for this and also other reasons).

Based on your comment I don't expect you to agree, but maybe somebody else will pick up on these comments. For my part, now that I now that this can happen, I will add checksum checks at user level. 

(and just FYI, I abandoned ZFS on Linux, because it caused kernel crashed every once in a while. I bet that is also caused by a mindset of "if the hardware does not behave as expected, it's not my problem")

**Comment by oneptr** [comment]
PS:
One thing I didn't explicitly mention: If I hadn't tried to unsquash the file, I would not have noticed that anything is wrong. Eventually I would have realized that the content of the files got swapped. That's kind of the worst scenario, when your data are corrupted in a very subtle way and you don't know it. Imagine you attach a file to an e-mail having this content (based on the name), when in fact the content is that of another confidental file...
