### ISSUE TITLE
Feature enchancement: Need feature to change endianness of file system

### ISSUE THREAD

**Issue by arjuncr** [plougher/squashfs-tools#81]
Need feature to convert big endian squashfs to little endian and vice versa.

**Comment by plougher** [comment]
Squashfs 4.0 filesystems are fixed little-endian.  There are no big-endian 4.0 filesystems.

Pre-4.0 Squashfs filesystems could be little or big endian, but, pre 4.0 filesystems are over 11 years old and obsolete.

If you want to convert them, you can use Unsquashfs to extract the contents, and then use Mksquashfs to re-compress them in what-ever byte ordering you want..   Obviously, this is using pre-4.0 Mksquashfs.
