### ISSUE TITLE
Reset timestamps in existing image

### ISSUE THREAD

**Issue by abitrolly** [plougher/squashfs-tools#90]
Can these tools reset timestamps in existing SquashFS archive to make the archive reproducible? Setting them to SOURCE_DATE_EPOCH, for example. Ideally, without mounting/unmounting.

**Comment by plougher** [comment]
Mksquashfs is designed to only append to existing archives, without rewriting any existing content.  This is deliberate as most people don't want the existing archive touched.

To reset the timestamps in the existing archive will therefore require a major enhancement to Mksquashfs, which unless a lot of people ask for it, cannot be justified within the limited resources available.
