### ISSUE TITLE
Unable to unsquashfs

### ISSUE THREAD

**Issue by tachang** [plougher/squashfs-tools#92]
Getting an issue where I can't seem to `unsquash` a specific file (/etc/fstab). Not sure exactly what the best course of action is to debug.

```
# ./unsquashfs -d /tmp/newroot -f rootfs.squashfs /etc/fstab
Parallel unsquashfs: Using 1 processor
read_xattrs_from_disk
1 inodes (1 blocks) to write


FATAL ERROR:write_file: unable to malloc block list
```

The source makes it seem like it is a malloc issue but it is only 1 block and 1 inode. Other files work fine. This is on MIPS 32 bit little endian cross compiled.

I tried to unsquashfs this on the host system (Ubuntu) and it worked fine.

# unsquashfs -v
unsquashfs version 4.3 (2014/05/12)

Also tried to verify it wasn't corrupt and I was using the same file so I moved it over to the MIPS embedded system and md5sum'ed and it matched on both systems.

```
# md5sum rootfs.squashfs 
b00afbd4cc032488709ecdc224362d69  rootfs.squashfs
```

**Comment by AgentD** [comment]
> ```
> create_inode: pathname /tmp/newroot/etc/fstab
> create_inode: regular file, file_size 320, blocks 0
> write_file: regular file, blocks 0
> ```

The file is 320 bytes in size and stored in a fragment block, so it doesn't have any blocks on its own.

A quick `git grep` for your error message leads me to [this code snippet](https://github.com/plougher/squashfs-tools/blob/master/squashfs-tools/unsquashfs.c#L997) in `unsquashfs.c`:

> ```c
>	block_list = malloc(inode->blocks * sizeof(unsigned int));
>	if(block_list == NULL)
>		EXIT_UNSQUASH("write_file: unable to malloc block list\n");
> ```

If `inode->blocks` is 0 (as is in your case), the argument to `malloc` is 0. The C standard specifies that a `malloc` request for 0 bytes is implementation defined and can result in "... either a null, pointer or a unique pointer."

I take it the glibc on your Ubuntu system does the later, while the libc on your MIPS platform does the former?

**Comment by AgentD** [comment]
@tachang does this patch fix your problem?

[0001-Fix-file-extraction-for-systems-where-malloc-0-retur.patch.gz](https://github.com/plougher/squashfs-tools/files/5185276/0001-Fix-file-extraction-for-systems-where-malloc-0-retur.patch.gz)

**Comment by tachang** [comment]
Thanks for taking a look. I am using uclibc cross compiled on the MIPS platform.

**Comment by tachang** [comment]
Looks good!

```
# patch -p 1 < custom.patch 
patching file squashfs-tools/unsquashfs.c

# make squashfs-rebuild

# ./unsquashfs test.squashfs 
Parallel unsquashfs: Using 1 processor
1 inodes (1 blocks) to write

[==============================================================================================================================================================================|] 1/1 100%

created 1 files
created 1 directories
created 0 symlinks
created 0 devices
created 0 fifos


# file unsquashfs 
unsquashfs: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-uClibc.so.0, not stripped

# ldd unsquashfs 
	libpthread.so.1 => /lib/libpthread.so.1 (0x77f77000)
	libm.so.1 => /lib/libm.so.1 (0x77f59000)
	libz.so.1 => /usr/lib/libz.so.1 (0x77f32000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x77ef9000)
	libc.so.1 => /lib/libc.so.1 (0x77e70000)
	ld-uClibc.so.1 => /lib/ld-uClibc.so.0 (0x77f9c000)
	libdl.so.1 => /lib/libdl.so.1 (0x77e5c000)
# 

SQUASHFS_VERSION = 4.4
SQUASHFS_SOURCE = squashfs$(SQUASHFS_VERSION).tar.gz
SQUASHFS_SITE = http://downloads.sourceforge.net/project/squashfs/squashfs/squashfs$(SQUASHFS_VERSION)

```

**Comment by tachang** [comment]
I guess to be as cross platform as possible it makes sense not to assume you'll get a unique pointer back from `malloc`.

Surprised no one else ran into this as squashfs is used on a lot of embedded systems?

**Comment by plougher** [comment]
Squashfs-tools are tested on glibc().  Fixed.
