### ISSUE TITLE
Reducing amount of cores mksquashfs uses

### ISSUE THREAD

**Issue by heinihuber** [plougher/squashfs-tools#97]
My notebook (Asus UX550VD) seems to have a bad thermal design what makes it to crash completely on using mksquashfs after some minutes. The option (-processors) does not work to reduce the amount of cores that is used - would you be able to implement such feature that enables to reduce the workload on systems with only one CPU installed?

Kind regards!

**Comment by plougher** [comment]
I have added two options which should limit the I/O and CPU usage of Mksquashfs (in addition to -processors 1 option).

-throttle <percentage> has the semantics of throttle the reader by X%.  The higher the percentage, the greater the throughput of the reader thread is reduced.

-limit <percentage> has the opposite sense of limit the output to X%.  The higher the percentage, the greater the throughput of the reader thread.

So

% mksquashfs XXX img.sqsh -throttle 50

Should limit the input rate of Mksquashfs to 50%, which will reduce the amount of I/O and CPU usage of Mksquashfs.

Obviously higher rates will reduce the input by more, with 90% meaning Mksquashfs will only read for 10% of the available time.
