### ISSUE TITLE
Mksquashfs - Fatal Error when network output location 

### ISSUE THREAD

**Issue by olsztyn1** [plougher/squashfs-tools#99]
Executing ISO-Snapshot tool, which calls mksquashfs to create a squashed file output  is successful when the output location is local but results in fatal error when output location is on network SMB share.
Is this a known limitation of mksquashfs or is this supposed to work and the cause of the issue is elsewhere?
Environment details:
- Debian based antiX linux.  ISO-Snapshot tool takes a snapshot of running system and creates squashed output.
- Location of output is on SMB 2.0 (or 2.1) share. Share is visible and accessible from file manager (SpaceFM).
Any help in resolving this will be greatly appreciated...
Thanks and Regards.

**Comment by plougher** [comment]
Mksquashfs uses standard library calls to open and read/write the output filesystem image.

These library calls are filesystem agnostic, and they should behave no differently irrespective of the filesystem being output to.

If Mksquashfs produces a fatal error on one filesystem only, especially if it is a network filesystem, the most likely cause is a issue with that filesystem or a networking issue.
